platform :ios, '6.0'

pod 'ReactiveCocoa', '~>2.3'
pod 'FrameAccessor', '~>1.3.2'
pod 'SVProgressHUD', '~>1.0'
pod 'FlurrySDK', '~>5.0.0'
pod 'pop', '~> 1.0'
pod 'UIImage+Additions', '~>1.1.0'
pod 'SSKeychain'
